### ISSUE TITLE
belt-ctr implementation

### ISSUE THREAD

**Issue by makavity** [RustCrypto/block-modes#35]
Hello!
Just tried to implement STB 34.101.31-2020 belt-ctr cipher:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/5614215/222424602-a47ed18e-1416-4787-ac1b-3e1f64189e66.png">

With code:
```rust
pub type BeltCtr = ctr::Ctr128LE<belt_block::BeltBlock>;

#[cfg(test)]
mod tests {
    use ctr::cipher::{KeyIvInit, StreamCipher};
    use hex_literal::hex;
    use super::*;

    #[test]
    fn test() {
        let x = hex!("B194BAC8 0A08F53B 366D008E 584A5DE4 8504FA9D 1BB6C7AC 252E72C2 02FDCE0D 5BE3D612 17B96181 FE6786AD 716B890B");
        let k = hex!("E9DEE72C 8F0C0FA6 2DDB49F4 6F739647 06075316 ED247A37 39CBA383 03A98BF6");
        let s = hex!("BE329713 43FC9A48 A02A885F 194B09A1");
        let y = hex!("52C9AF96 FF50F644 35FC43DE F56BD797 D5B5B1FF 79FB4125 7AB9CDF6 E63E81F8 F0034147 3EAE4098 33622DE0 5213773A");

        let mut cipher = BeltCtr::new(&k.into(), &s.into());
        let mut buf = x.to_vec();
        cipher.apply_keystream(&mut buf);
        assert_eq!(buf, y);
    }
}
```

And got some problems:
gen_ks_block return bytes:
```
72 8a f3 c2   9a e7 56 4f 
54 01 c9 10   13 31 d8 a4
```

But in STB, we need to add +1 in LE (so, bytes will be):
```
73 8a f3 c2   9a e7 56 4f  
54 01 c9 10   13 31 d8 a3
```

And it should be reversed. What I suppose to do, to resolve this problem? Implement self own gen_ks_block?
Thank you!
@newpavlov

**Comment by newpavlov** [comment]
I think it will be better to implement the mode in a separate crate. In addition to not counting from 0, the specification also encrypts IV before using it with counter.

**Comment by makavity** [comment]
Should I create crate stub-modes, like gost-modes?

**Comment by newpavlov** [comment]
Hm, I am not sure. If you do not plan to implement the other modes, then I think we can publish it under `belt-ctr` for now. The mode could be defined generically, but would use `belt-block` by default.

**Comment by makavity** [comment]
I need to implement ecb, cfb, ctr modes, also belt-mac and bign (elliptic curves) :)

**Comment by makavity** [comment]
And also, should I PR into stream-ciphers with belt-ctr?
What about repo for ecb and mac?

**Comment by newpavlov** [comment]
Since we keep the `ctr` crate in this repository, `belt-ctr` should go here as well.

I think `belt-cfb` should be compatible with implementation in `cfb-mode`. Can you check it?

`belt-ecb` and `belt-cbc` use variation of the classic ciphertext stealing, but with the tweak for messages with length multiple of the block size. They can go into this repository with inherent methods for encryption and decryption since we currently do not have traits for ciphertext stealing algorithms.

`belt-mac` looks like CMAC, but I am not sure that padding handling is the same. If not, we would need a separate crate in the [MACs repository](https://github.com/RustCrypto/MACs).

For elliptic curves take a look at the [`primeorder`](https://github.com/RustCrypto/elliptic-curves/tree/master/primeorder) crate. If you have any questions about it, I think it will be better to ask @tarcieri in our Zulip chat.

**Comment by makavity** [comment]
Belt-cfb is compatible, just checked it right now.
Ecb is not compatible, because stealing, right.

Okay, thank you for help!
If I have any question - I will ask :)
